services:
  cloudflare-ddns:
    image: timothyjmiller/cloudflare-ddns@sha256:2187e122660d6a2d451ef7c53fd4805c133133f4f47552256352c1e2a7f49ee2
    container_name: homelab-cloudflare-ddns
    security_opt:
      - no-new-privileges:true
    network_mode: 'host'
    env_file: ".env"
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./cloudflare-ddns/config.json:/config.json
    restart: unless-stopped
