kind: Deployment
apiVersion: apps/v1
metadata:
  name: adguard-home
  labels:
    part-of: infraestructure
spec:
  selector:
    matchLabels:
      app: adguard-home
  template:
    metadata:
      labels:
        app: adguard-home
    spec:
      containers:
        - name: adguard-home
          image: adguard/adguardhome:v0.107.63@sha256:a1bd0d8640c46eb59989cef3c1366bc7b0ac67d3260d9e1c99e1d2b3a9eb8422
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 53
              protocol: TCP
            - containerPort: 53
              protocol: UDP
            - containerPort: 80
              protocol: TCP
            - containerPort: 443
              protocol: TCP
            - containerPort: 443
              protocol: UDP
            - containerPort: 3000
              protocol: TCP
          resources:
            requests:
              cpu: 0.5
              memory: 128mb
            limits:
              cpu: 1
              memory: 512mb
          livenessProbe:
            tcpSocket:
              port: 53
            timeoutSeconds: 5
            # initialDelaySeconds: 10